import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, addDoc, query, where, orderBy, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyD2SkmRy9xHIhWIVBSoQBEtCs9GE5o1JtY",authDomain:"psss-dec9e.firebaseapp.com",projectId:"psss-dec9e",storageBucket:"psss-dec9e.firebasestorage.app",messagingSenderId:"1066121156105",appId:"1:1066121156105:web:badd570a14aaa394dccad8"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let profile=null,currentChat=null,unsubChats=null,unsubMessages=null;
const clean=u=>u.trim().toLowerCase().replace(/[^a-z0-9._-]/g,"");const emailFor=u=>`${clean(u)}@psss.local`;const passwordFor=p=>`Psss!${p}#2026`;const esc=t=>{const d=document.createElement('div');d.textContent=t;return d.innerHTML};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.tab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.tab!=='register');$('#authMsg').textContent=''});
$('#registerForm').onsubmit=async e=>{e.preventDefault();const displayName=$('#displayName').value.trim(),username=clean($('#registerUser').value),pin=$('#registerPin').value.trim(),master=$('#masterInvite').value.trim();try{if(master!=='PSSS-2026')throw Error('Ungültiger Einladungscode.');if(username.length<3)throw Error('Benutzername zu kurz.');if(!/^\d{4,8}$/.test(pin))throw Error('PIN: 4 bis 8 Zahlen.');const c=await createUserWithEmailAndPassword(auth,emailFor(username),passwordFor(pin));const invite='PSSS-'+crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase();await setDoc(doc(db,'users',c.user.uid),{displayName,username,invite,createdAt:serverTimestamp()});await setDoc(doc(db,'inviteCodes',invite),{uid:c.user.uid,displayName,username,createdAt:serverTimestamp()});}catch(err){$('#authMsg').textContent=friendly(err)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,emailFor($('#loginUser').value),passwordFor($('#loginPin').value.trim()))}catch(err){$('#authMsg').textContent=friendly(err)}};
function friendly(err){console.error(err);if(err.code==='auth/email-already-in-use')return'Dieser Benutzername ist vergeben.';if(err.code==='auth/invalid-credential')return'Benutzername oder PIN ist falsch.';if(err.code==='auth/network-request-failed')return'Keine Internetverbindung.';return err.message||'Fehler.'}
onAuthStateChanged(auth,async user=>{if(!user){profile=null;$('#auth').classList.remove('hidden');$('#app').classList.add('hidden');return}const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists()){await signOut(auth);return}profile={uid:user.uid,...snap.data()};$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#me').textContent=profile.displayName;$('#myInvite').textContent=profile.invite;listenChats()});
function listenChats(){if(unsubChats)unsubChats();const q=query(collection(db,'chats'),where('participants','array-contains',profile.uid));unsubChats=onSnapshot(q,s=>{const rows=[];s.forEach(d=>rows.push({id:d.id,...d.data()}));rows.sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));$('#chatList').innerHTML=rows.length?rows.map(c=>{const other=c.members?.find(m=>m.uid!==profile.uid)||{displayName:'Unbekannt'};return `<div class="chatitem ${currentChat?.id===c.id?'active':''}" data-id="${c.id}"><div class="avatar">${esc(other.displayName[0]||'?')}</div><div><b>${esc(other.displayName)}</b><div class="preview">${esc(c.lastMessage||'Noch keine Nachricht')}</div></div></div>`}).join(''):'<p style="padding:16px;color:var(--muted)">Noch keine Chats.</p>';$$('.chatitem').forEach(el=>el.onclick=()=>openChat(rows.find(x=>x.id===el.dataset.id)))})}
async function openChat(c){currentChat=c;const other=c.members.find(m=>m.uid!==profile.uid);$('#empty').classList.add('hidden');$('#chat').classList.remove('hidden');$('#chatName').textContent=other.displayName;$('#avatar').textContent=other.displayName[0].toUpperCase();if(unsubMessages)unsubMessages();const q=query(collection(db,'chats',c.id,'messages'),orderBy('createdAt','asc'));unsubMessages=onSnapshot(q,s=>{const rows=[];s.forEach(d=>rows.push(d.data()));$('#messages').innerHTML=rows.map(m=>`<div class="bubble ${m.senderId===profile.uid?'mine':''}"><div>${esc(m.text)}</div><div class="time">${m.createdAt?.toDate?m.createdAt.toDate().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):''}</div></div>`).join('');$('#messages').scrollTop=$('#messages').scrollHeight});$('#side').classList.remove('open')}
$('#sendForm').onsubmit=async e=>{e.preventDefault();const text=$('#text').value.trim();if(!text||!currentChat)return;$('#text').value='';await addDoc(collection(db,'chats',currentChat.id,'messages'),{text,senderId:profile.uid,createdAt:serverTimestamp()});await setDoc(doc(db,'chats',currentChat.id),{lastMessage:text,updatedAt:serverTimestamp()},{merge:true})};
$('#inviteBtn').onclick=()=>{$('#friendCode').value='';$('#inviteMsg').textContent='';$('#inviteDialog').showModal()};$('#cancelInvite').onclick=()=>$('#inviteDialog').close();
$('#inviteForm').onsubmit=async e=>{e.preventDefault();try{const code=$('#friendCode').value.trim().toUpperCase(),inv=await getDoc(doc(db,'inviteCodes',code));if(!inv.exists())throw Error('Einladungscode nicht gefunden.');const other=inv.data();if(other.uid===profile.uid)throw Error('Das ist dein eigener Code.');const ids=[profile.uid,other.uid].sort(),chatId=ids.join('_');await setDoc(doc(db,'chats',chatId),{participants:ids,members:[{uid:profile.uid,displayName:profile.displayName},{uid:other.uid,displayName:other.displayName}],lastMessage:'',updatedAt:serverTimestamp()},{merge:true});$('#inviteDialog').close()}catch(err){$('#inviteMsg').textContent=err.message}};
$('#copyInvite').onclick=async()=>{await navigator.clipboard.writeText(profile.invite);$('#copyInvite').textContent='Kopiert';setTimeout(()=>$('#copyInvite').textContent='Kopieren',1200)};$('#logout').onclick=()=>signOut(auth);$('#menu').onclick=()=>$('#side').classList.toggle('open');function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('psss_theme',t)}$('#theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');setTheme(localStorage.getItem('psss_theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));